plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    modImplementation("com.terraformersmc:modmenu:${rootProject.modmenu_version}") { transitive = false }
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = rootProject.group
            artifactId = "Boxlib-$project.name"
            version = rootProject.version
        }
    }

    def user = System.getenv("MAVEN_USER")
    def pass = System.getenv("MAVEN_PASS")

    if (user && pass) {
        repositories {
            maven {
                url = uri("https://maven.boxadactle.dev/releases")
                credentials {
                    username = user
                    password = pass
                }
            }

            maven {
                url = uri("https://maven.boxadactle.dev/snapshots")
                credentials {
                    username = user
                    password = pass
                }
            }
        }
    } else {
        println "Skipping Maven repository upload, no credentials provided."
    }
}