plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven { url = "https://maven.terraformersmc.com/releases/" }
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	modImplementation("com.terraformersmc:modmenu:${rootProject.modmenu_version}") {
		transitive = false
	}
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 8
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_1_8
	targetCompatibility = JavaVersion.VERSION_1_8
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
def snapshotenv = System.getenv("IS_SNAPSHOT_PUBLISH")
def snapshotRepo = snapshotenv ? snapshotenv.toBoolean() : true

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	def user = System.getenv("MAVEN_USER")
	def pass = System.getenv("MAVEN_PASS")

	if (user && pass) {
		repositories {
			if (!snapshotRepo) {
				maven {
					url = uri("https://maven.boxadactle.dev/releases")
					credentials {
						username = user
						password = pass
					}
				}
			}

			else {
				maven {
					url = uri("https://maven.boxadactle.dev/snapshots")
					credentials {
						username = user
						password = pass
					}
				}
			}
		}
	} else {
		println "Skipping Maven repository upload, no credentials provided."
	}
}

publishMods {
	file = remapJar.archiveFile
	type = STABLE
	modLoaders.add("fabric")
	displayName = "${mod_version}-fabric"

	curseforge {
		accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
		projectId = project_id_curseforge
		minecraftVersions.addAll(game_versions.split(","))
	}

	modrinth {
		accessToken = providers.environmentVariable("MODRINTH_TOKEN")
		projectId = project_id_modrinth
		minecraftVersions.addAll(game_versions.split(","))
	}

	github {
		accessToken = providers.environmentVariable("GITHUB_TOKEN")
		repository = "Boxadactle/BoxLib"
		commitish = "dev"
	}
}
