plugins {
    id 'dev.architectury.loom' version '1.10-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
    id "me.modmuss50.mod-publish-plugin" version "0.8.4"
    id "com.github.breadmoirai.github-release" version "2.5.2"
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'

    if (!project.name.contains("boxlib")) {
        base {
            // Set up a suffixed format for the mod jar names, e.g. `example-fabric`.
            archivesName = "$rootProject.archives_name-$project.name"
        }
    }

    repositories {
        maven { url = "https://maven.terraformersmc.com/releases/" }
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
        mappings loom.officialMojangMappings()
    }

    processResources {
        var expandProps = [
                'version'                      : rootProject.mod_version,
                'group'                        : rootProject.maven_group,
                'minecraft_version'            : rootProject.minecraft_version,
                'minecraft_version_range'      : rootProject.minecraft_version_range,
                'miencraft_version_range_fabric': rootProject.minecraft_version_range_fabric,
                'fabric_version'               : rootProject.fabric_api_version,
                'fabric_loader_version'        : rootProject.fabric_loader_version,
                'mod_name'                     : rootProject.archives_name,
                'mod_author'                   : rootProject.mod_author,
                'mod_id'                       : rootProject.mod_id,
                'license'                      : rootProject.license,
                'description'                  : rootProject.project.description,
                'neoforge_version'             : rootProject.neoforge_version,
                'neoforge_loader_version_range': rootProject.neoforge_loader_version_range,
                "forge_version"                 : rootProject.forge_version,
                "forge_loader_version_range"    : rootProject.forge_loader_version_range,
        ]

        var jsonExpandProps = expandProps.collectEntries {
            key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
        }

        filesMatching(['META-INF/mods.toml', 'META-INF/neoforge.mods.toml']) {
            expand expandProps
        }

        filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) {
            expand jsonExpandProps
        }

        inputs.properties(expandProps)
    }

    java {
        // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
        // if it is present.
        // If you remove this line, sources will not be generated.
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_22
        targetCompatibility = JavaVersion.VERSION_22
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }

    if (!project.name.contains("testmod")) {
        def snapshotenv = System.getenv("IS_SNAPSHOT_PUBLISH")
        def snapshotRepo = snapshotenv ? snapshotenv.toBoolean() : true

        publishing {
            publications {
                mavenJava(MavenPublication) {
                    groupId = rootProject.group
                    version = rootProject.version

                    if (snapshotRepo) artifactId = "Boxlib-$project.name-snapshot"
                    else artifactId = "Boxlib-$project.name"
                }
            }

            def user = System.getenv("MAVEN_USER")
            def pass = System.getenv("MAVEN_PASS")

            if (user && pass) {
                repositories {
                    if (!snapshotRepo) {
                        maven {
                            url = uri("https://maven.boxadactle.dev/releases")
                            credentials {
                                username = user
                                password = pass
                            }
                        }
                    }

                    else {
                        maven {
                            url = uri("https://maven.boxadactle.dev/snapshots")
                            credentials {
                                username = user
                                password = pass
                            }
                        }
                    }
                }
            } else {
                println "Skipping Maven repository upload, no credentials provided."
            }
        }
    }
}

publishMods {
    changelog = new File(rootProject.rootDir, project.changelog_file).text
    type = STABLE

    def cfOptions = curseforgeOptions {
        accessToken = System.getenv("CURSEFORGE_TOKEN")
        projectId = project.project_id_curseforge
        minecraftVersions.addAll(project.game_versions.split(","))
        changelogType = "markdown"
        javaVersions.add(JavaVersion.current())
    }

    def mrOptions = modrinthOptions {
        accessToken = System.getenv("MODRINTH_TOKEN")
        projectId = project.project_id_modrinth
        minecraftVersions.addAll(project.game_versions.split(","))
    }

    curseforge("curseforgeFabric") {
        from cfOptions
        file project(":fabric")
        modLoaders.addAll("fabric", "quilt")
        requires {
            slug = "fabric-api"
        }
        displayName = "[Fabric ${project.minecraft_version}] v${project.version}"
    }

    curseforge("curseforgeForge") {
        from cfOptions
        file project(":forge")
        modLoaders.add("forge")
        displayName = "[Forge ${project.minecraft_version}] v${project.version}"
    }

    curseforge("curseforgeNeoforge") {
        from cfOptions
        file project(":neoforge")
        modLoaders.add("neoforge")
        displayName = "[Neoforge ${project.minecraft_version}] v${project.version}"
    }

    modrinth("modrinthFabric") {
        from mrOptions
        file project(":fabric")
        modLoaders.addAll("fabric", "quilt")
        requires {
            slug = "fabric-api"
        }
        displayName = "[Fabric ${project.minecraft_version}] v${project.version}"
    }

    modrinth("modrinthForge") {
        from mrOptions
        file project(":forge")
        modLoaders.add("forge")
        displayName = "[Forge ${project.minecraft_version}] v${project.version}"
    }

    modrinth("modrinthNeoforge") {
        from mrOptions
        file project(":neoforge")
        modLoaders.add("neoforge")
        displayName = "[Neoforge ${project.minecraft_version}] v${project.version}"
    }
}

githubRelease {
    owner = "Boxadactle"
    repo = "BoxLib"
    tagName = "$project.version"
    targetCommitish = "dev"
    releaseName = "BoxLib $project.version"
    generateReleaseNotes = true
    body = """BoxLib $project.version for Minecraft $project.minecraft_version

${new File(rootProject.rootDir, project.changelog_file).text}
"""
    authorization = "Token ${System.getenv("GITHUB_TOKEN")}"

    var files = []
    for (String platform : project.enabled_platforms.split(',')) {
        files += fileTree("$platform/build/libs") {
            include "*$project.version*"
        }
    }
    releaseAssets = files

//    dryRun = true
}