modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "boxlib"
version = "${version}"
displayName = "BoxLib"
authors = "Boxadactle"
description = '''
The most basic client-slide mod
'''
logoFile = "icon.png"

[[dependencies.boxlib]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.boxlib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "neoforge.boxlib.mixins.json"

[[mixins]]
config = "boxlib.mixins.json"
