modLoader="javafml"
loaderVersion="[0,)"
license="MIT"

[[mods]]
modId = "boxlibtestmod"
version = "0.0.0"
displayName = "Boxlib Test Mod"
authors = "Boxadactle"
description = '''
The most basic client-side mod
'''
logoFile = "icon.png"

[[dependencies.boxlibtestmod]]
modId="forge"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.boxlibtestmod]]
modId="minecraft"
mandatory=true
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"
