modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "boxlib-testmod"
version = "${version}"
displayName = "Boxlib Test Mod"
authors = "Boxadactle"
description = '''
The most basic client-side mod
'''
logoFile = "icon.png"

[[dependencies.boxlib-testmod]]
modId = "neoforge"
type = "required"
versionRange = "[20.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.boxlib-testmod]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,)"
ordering = "NONE"
side = "BOTH"
